const keys = ['title9','title10','choose9','choose10','start','next','finish','again','menu','settings','all','verbs','tense','count','present','past','future','man','woman','men','women','sound','list','stats','help','close','correct','wrong','completed','result','empty','listen','missing','preview','previewNote','show','heardFirst','audioError','exitTitle','exitBody','cancel','leave','hidden','pinned','restore','unpin','sessions','best','average','saveError','loading','translit','available'];
const lines = {
 ru: ['Глагол в предложении','Услышь и пойми','Выберите форму глагола','Прослушайте и выберите перевод','НАЧАТЬ','ДАЛЕЕ','ЗАВЕРШИТЬ','ЕЩЁ РАЗ','В МЕНЮ','Настройки','Все','Глаголы','Время','Количество заданий','Настоящее','Прошедшее','Будущее','Мужчина','Женщина','Мужчины / смешанная группа','Женщины','Звук','Повторение','Статистика','Как заниматься','Закрыть','Верно','Неверно','Упражнение завершено','Результат','Нет доступных заданий. Проверьте фильтры, исключения и базу.','Прослушать','Озвучка пока не подключена','Проверка без аудио','Проверка интерфейса. Результат не сохраняется.','Показать фразу','Сначала прослушайте предложение','Не удалось воспроизвести. Попробуйте ещё раз.','Выйти из задания?','Незавершённая сессия не попадёт в статистику.','Отмена','Выйти','Исключено','Чаще','Вернуть','Убрать приоритет','Завершено','Лучший результат','Средний результат','Не удалось сохранить результат','Загрузка…','Транслитерация','Доступно'],
 en: ['Verb in a sentence','Listen and understand','Choose the verb form','Listen and choose the translation','START','NEXT','FINISH','AGAIN','MENU','Settings','All','Verbs','Tense','Number of tasks','Present','Past','Future','Man','Woman','Men / mixed group','Women','Sound','Review','Statistics','How to practise','Close','Correct','Incorrect','Exercise completed','Result','No tasks available. Check filters, exclusions and data.','Listen','Audio is not connected yet','Preview without audio','Interface preview. Results are not saved.','Show sentence','Listen to the sentence first','Playback failed. Please try again.','Leave this session?','An unfinished session will not be saved to statistics.','Cancel','Leave','Hidden','More often','Restore','Unpin','Completed','Best score','Average score','Could not save the result','Loading…','Transliteration','Available'],
 fr: ['Le verbe dans la phrase','Écouter et comprendre','Choisissez la forme du verbe','Écoutez et choisissez la traduction','COMMENCER','SUIVANT','TERMINER','ENCORE','MENU','Paramètres','Tous','Verbes','Temps','Nombre de questions','Présent','Passé','Futur','Homme','Femme','Hommes / groupe mixte','Femmes','Son','Révision','Statistiques','Comment pratiquer','Fermer','Correct','Incorrect','Exercice terminé','Résultat','Aucune question disponible. Vérifiez les filtres, les exclusions et les données.','Écouter',"L’audio n’est pas encore disponible",'Aperçu sans audio','Aperçu de l’interface. Résultats non enregistrés.','Afficher la phrase','Écoutez d’abord la phrase','Échec de la lecture. Réessayez.','Quitter la session ?','Une session inachevée ne sera pas enregistrée.','Annuler','Quitter','Masqués','Plus souvent','Rétablir','Retirer la priorité','Terminés','Meilleur score','Score moyen','Impossible d’enregistrer le résultat','Chargement…','Translittération','Disponibles'],
 es: ['El verbo en la oración','Escucha y comprende','Elige la forma del verbo','Escucha y elige la traducción','EMPEZAR','SIGUIENTE','TERMINAR','OTRA VEZ','MENÚ','Ajustes','Todos','Verbos','Tiempo','Número de preguntas','Presente','Pasado','Futuro','Hombre','Mujer','Hombres / grupo mixto','Mujeres','Sonido','Repaso','Estadísticas','Cómo practicar','Cerrar','Correcto','Incorrecto','Ejercicio terminado','Resultado','No hay preguntas disponibles. Revisa los filtros, las exclusiones y los datos.','Escuchar','El audio aún no está disponible','Vista previa sin audio','Prueba de interfaz. Los resultados no se guardan.','Mostrar oración','Escucha primero la oración','No se pudo reproducir. Inténtalo de nuevo.','¿Salir de la sesión?','Una sesión incompleta no se guardará en las estadísticas.','Cancelar','Salir','Ocultos','Más a menudo','Restaurar','Quitar prioridad','Completados','Mejor resultado','Resultado medio','No se pudo guardar el resultado','Cargando…','Transliteración','Disponibles'],
 pt: ['O verbo na frase','Ouça e compreenda','Escolha a forma do verbo','Ouça e escolha a tradução','COMEÇAR','SEGUINTE','CONCLUIR','NOVAMENTE','MENU','Configurações','Todos','Verbos','Tempo','Número de questões','Presente','Passado','Futuro','Homem','Mulher','Homens / grupo misto','Mulheres','Som','Revisão','Estatísticas','Como praticar','Fechar','Correto','Incorreto','Exercício concluído','Resultado','Nenhuma questão disponível. Verifique os filtros, as exclusões e os dados.','Ouvir','O áudio ainda não está disponível','Prévia sem áudio','Teste da interface. Os resultados não são salvos.','Mostrar frase','Ouça a frase primeiro','Falha na reprodução. Tente novamente.','Sair da sessão?','Uma sessão incompleta não será salva nas estatísticas.','Cancelar','Sair','Ocultos','Mais vezes','Restaurar','Remover prioridade','Concluídos','Melhor resultado','Resultado médio','Não foi possível salvar o resultado','Carregando…','Transliteração','Disponíveis'],
 ar: ['الفعل في الجملة','استمع وافهم','اختر صيغة الفعل','استمع واختر الترجمة','ابدأ','التالي','إنهاء','مرة أخرى','القائمة','الإعدادات','الكل','الأفعال','الزمن','عدد الأسئلة','الحاضر','الماضي','المستقبل','رجل','امرأة','رجال / مجموعة مختلطة','نساء','الصوت','المراجعة','الإحصاءات','كيفية التدريب','إغلاق','صحيح','غير صحيح','اكتمل التمرين','النتيجة','لا توجد أسئلة متاحة. تحقق من المرشحات والاستثناءات والبيانات.','استمع','التسجيل الصوتي غير متاح بعد','معاينة بدون صوت','معاينة الواجهة. لن تُحفظ النتائج.','عرض الجملة','استمع إلى الجملة أولًا','تعذر التشغيل. حاول مرة أخرى.','مغادرة الجلسة؟','لن تُحفظ الجلسة غير المكتملة في الإحصاءات.','إلغاء','مغادرة','مستبعد','بتكرار أكبر','استعادة','إزالة الأولوية','المكتمل','أفضل نتيجة','متوسط النتيجة','تعذر حفظ النتيجة','جارٍ التحميل…','النطق بالحروف اللاتينية','المتاح'],
 am: ['በዓረፍተ ነገር ውስጥ ያለ ግስ','አዳምጥ እና ተረዳ','የግሱን ቅርጽ ይምረጡ','አዳምጠው ትርጉሙን ይምረጡ','ጀምር','ቀጣይ','ጨርስ','እንደገና','ምናሌ','ቅንብሮች','ሁሉም','ግሶች','ጊዜ','የጥያቄዎች ብዛት','አሁን','ያለፈ','ወደፊት','ወንድ','ሴት','ወንዶች / ድብልቅ ቡድን','ሴቶች','ድምፅ','ድገማ','ስታቲስቲክስ','እንዴት መለማመድ ይቻላል','ዝጋ','ትክክል','ትክክል አይደለም','ልምምዱ ተጠናቋል','ውጤት','ጥያቄዎች የሉም። ማጣሪያዎችን እና መረጃውን ያረጋግጡ።','አዳምጥ','ድምፅ ገና አልተጨመረም','ያለ ድምፅ ቅድመ እይታ','የማያ ገጽ ሙከራ። ውጤቶች አይቀመጡም።','ዓረፍተ ነገሩን አሳይ','መጀመሪያ ዓረፍተ ነገሩን ያዳምጡ','ድምፁን ማጫወት አልተቻለም። እንደገና ይሞክሩ።','ከልምምዱ ይውጡ?','ያልተጠናቀቀ ልምምድ አይቀመጥም።','ይቅር','ውጣ','የተደበቀ','ብዙ ጊዜ','መልስ','ቅድሚያውን አስወግድ','የተጠናቀቀ','ምርጥ ውጤት','አማካይ ውጤት','ውጤቱን ማስቀመጥ አልተቻለም','በመጫን ላይ…','በላቲን ፊደላት','የሚገኙ']
};
export const UI = Object.fromEntries(Object.entries(lines).map(([lang,values])=>[lang,Object.fromEntries(keys.map((key,i)=>[key,values[i]]))]));
export const HELP = {

  ru: [
    'Подставьте правильную форму глагола в предложение. Учитывайте время, лицо и род. После ответа появятся перевод и транслитерация. Нажмите кнопку динамика, чтобы прослушать всё предложение целиком на иврите. Задания можно исключать из повторения или отмечать для более частого показа.',
    'Прослушайте предложение и выберите правильный перевод. После ответа откроются текст на иврите и транслитерация. Задания можно исключать из повторения или отмечать для более частого показа.'
  ],

  en: [
    'Choose the correct verb form to complete the sentence. Pay attention to tense, person and gender. Translation and transliteration appear after answering. Tap the speaker button to listen to the complete sentence in Hebrew. You can exclude tasks from review or mark them to appear more often.',
    'Listen to the sentence and choose the correct translation. Hebrew text and transliteration appear after answering. You can exclude tasks from review or mark them to appear more often.'
  ],

  fr: [
    'Choisissez la bonne forme du verbe pour compléter la phrase. Tenez compte du temps, de la personne et du genre. La traduction et la translittération apparaissent après la réponse. Appuyez sur le bouton du haut-parleur pour écouter la phrase complète en hébreu. Vous pouvez exclure certaines questions ou les faire apparaître plus souvent.',
    'Écoutez la phrase et choisissez la bonne traduction. Le texte en hébreu et la translittération apparaissent après la réponse. Vous pouvez exclure certaines questions ou les faire apparaître plus souvent.'
  ],

  es: [
    'Elige la forma correcta del verbo para completar la oración. Ten en cuenta el tiempo, la persona y el género. La traducción y la transliteración aparecen después de responder. Pulsa el botón del altavoz para escuchar la oración completa en hebreo. Puedes excluir preguntas o marcarlas para que aparezcan con más frecuencia.',
    'Escucha la oración y elige la traducción correcta. El texto en hebreo y la transliteración aparecen después de responder. Puedes excluir preguntas o marcarlas para que aparezcan con más frecuencia.'
  ],

  pt: [
    'Escolha a forma correta do verbo para completar a frase. Considere o tempo, a pessoa e o gênero. A tradução e a transliteração aparecem depois da resposta. Toque no botão do alto-falante para ouvir a frase completa em hebraico. Você pode excluir questões ou marcá-las para aparecerem com mais frequência.',
    'Ouça a frase e escolha a tradução correta. O texto em hebraico e a transliteração aparecem depois da resposta. Você pode excluir questões ou marcá-las para aparecerem com mais frequência.'
  ],

  ar: [
    'اختر صيغة الفعل الصحيحة لإكمال الجملة. انتبه إلى الزمن والشخص والجنس. تظهر الترجمة والكتابة الصوتية بعد الإجابة. اضغط على زر مكبر الصوت للاستماع إلى الجملة كاملة بالعبرية. يمكنك استبعاد بعض الأسئلة من التكرار أو جعلها تظهر بشكل أكثر تكرارًا.',
    'استمع إلى الجملة واختر الترجمة الصحيحة. يظهر النص العبري والكتابة الصوتية بعد الإجابة. يمكنك استبعاد بعض الأسئلة من التكرار أو جعلها تظهر بشكل أكثر تكرارًا.'
  ],

  am: [
    'ዓረፍተ ነገሩን ለማሟላት ትክክለኛውን የግስ ቅርጽ ይምረጡ። ጊዜን፣ ሰውን እና ጾታን ያስተውሉ። ከመልሱ በኋላ ትርጉሙ እና ትራንስሊተሬሽኑ ይታያሉ። ሙሉውን ዓረፍተ ነገር በዕብራይስጥ ለማዳመጥ የድምፅ ማጉያውን ቁልፍ ይጫኑ። ጥያቄዎችን ከድገማ ማስወገድ ወይም ብዙ ጊዜ እንዲታዩ ማድረግ ይችላሉ።',
    'ዓረፍተ ነገሩን ያዳምጡ እና ትክክለኛውን ትርጉም ይምረጡ። ከመልሱ በኋላ የዕብራይስጥ ጽሑፍ እና ትራንስሊተሬሽኑ ይታያሉ። ጥያቄዎችን ከድገማ ማስወገድ ወይም ብዙ ጊዜ እንዲታዩ ማድረግ ይችላሉ።'
  ]

};
